exports.questionType = {
  MCQ: "MCQ",
  FILL_IN_THE_BLANK: "FILL_IN_THE_BLANK",
  DESCRIPTIVE: "DESCRIPTIVE",
};

exports.assessmentSolutionStatus = {
  UNGRADED: "UNGRADED",
  GRADED: "GRADED",
  REGRADE_REQUESTED: "REGRADE REQUESTED",
};

exports.assessmentStatus = {
  AVAILABLE: "AVAILABLE",
  INACTIVE: "INACTIVE",
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
  UNGRADED: "UNGRADED",
  GRADED: "GRADED",
  CANCELLED: "CANCELLED",
  REGRADE_REQUESTED: "REGRADE REQUESTED",
};

exports.solutionGradingType = {
  AI_GRADING: "AI_GRADING",
  MANUAL_GRADING: "MANUAL_GRADING",
};
