exports.studentEvents = {
  STUDENT_REGISTRATION_REQUEST_NOTIFICATION:
    "STUDENT_REGISTRATION_REQUEST_NOTIFICATION",
};

exports.assessmentEvents = {
  ASSESSMENT_GRADED_NOTIFICATION: "ASSESSMENT_GRADED_NOTIFICATION",
  ASSESSMENT_REGRADED_NOTIFICATION: "ASSESSMENT_REGRADED_NOTIFICATION",
  ASSESSMENT_CREATED_NOTIFICATION: "ASSESSMENT_CREATED_NOTIFICATION",
};

exports.userEvents = {
  FORGOT_PASSWORD_OTP_REQUEST_NOTIFICATION:
    "FORGOT_PASSWORD_OTP_REQUEST_NOTIFICATION",
};

exports.classEvents = {
  ANNOUNCEMENT_POSTED: "ANNOUNCEMENT_POSTED",
};
