exports.TOKEN_TYPE = {
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
};

exports.PASSCODE_LENGTH = process.env.PASSCODE_LENGTH || 6;

exports.PASSCODE_INCORRECT_RETRIES =
  process.env.PASSCODE_INCORRECT_RETRIES || 3;
